HAI
    WAZZUP
        I HAS A var ITZ "a" BTW uninitialized var
    BUHBYE
    GIMMEH var
    VISIBLE SUM OF 3 AN 5
    VISIBLE SUM OF 6 AN 7
    VISIBLE SUM OF "WIN" AN WIN
    VISIBLE var
    VISIBLE SUM OF 8 AN 9
    var IS NOW A NUMBR
KTHXBYE