HAI
    WAZZUP
    I HAS A VAR ITZ 0
    BUHBYE
    VISIBLE NOT 0
    VISIBLE BOTH OF 1 AN 0
    VISIBLE BOTH OF "" AN 1
    VISIBLE BOTH OF WIN AN 1

    VISIBLE EITHER OF 0 AN 1
    VISIBLE EITHER OF "" AN 1
    VISIBLE EITHER OF WIN AN FAIL
    VISIBLE EITHER OF FAIL AN FAIL

    VISIBLE WON OF 1 AN 0
    VISIBLE WON OF 12 AN 3

    ALL OF NOT 1 AN BOTH OF 2 AN 0 AN EITHER OF WIN AN "" MKAY
    VISIBLE ALL OF NOT 1 AN BOTH OF 2 AN 0 AN EITHER OF WIN AN "" MKAY
    VISIBLE ANY OF NOT 1 AN BOTH OF 2 AN 0 AN EITHER OF WIN AN "" MKAY
    VISIBLE ALL OF NOT 0 AN BOTH OF 2 AN 1 AN EITHER OF WIN AN WIN MKAY
    VISIBLE ALL OF ALL OF NOT 1 AN BOTH OF 2 AN 0 AN EITHER OF 23 AN "" MKAY

KTHXBYE