HAI
    WAZZUP
    I HAS A VAR ITZ 2
    BUHBYE
    BTW VISIBLE 6 + 6
    VISIBLE MAEK VAR A TROOF
    VAR IS NOW A TROOF
    VAR IS NOW A NUMBR
    VAR IS NOW A TROOF
    VAR IS NOW A NUMBAR
    VISIBLE VAR
    15
    15.15
    WIN
    FAIL
    "LOL"
KTHXBYE